### ISSUE TITLE
MIME-encoded headers

### ISSUE THREAD

**Issue by rlaboiss** [rmanfredi/mailagent#1]
Hello Raphaël,

I have been using mailagent uninterruptedly since December 1998, so 25 years ago ! It is amazing how stable and still useful mailagent is today. 

However, I am facing a problem regarding encoded headers. Is there a way to make mailagent understand MIME-encoded headers ([RFC 2047](http://www.faqs.org/rfcs/rfc2047.html)), like `Subject: =?utf-8?Q?fianc=C3=A9e?=`, such that it can correctly filter the message with a rule like `Subject: /fiancée/ {SAVE weddings};`?

Best,

Rafael Laboissière

**Comment by rmanfredi** [comment]
Hello Rafael,

This is now implemented in the latest commit on the master branch.
Thank you for suggesting this feature and enjoy mailagent!

Cheers,
Raphaël

**Comment by rlaboiss** [comment]
Thanks for your prompt reaction, Raphaël!

I have tested your changes here, and it works like a charm.
